//using System.Text;
//using System.Text.Json;
//using FinCure.Configurations;
//using Microsoft.Extensions.Options;
//using System.Threading.Tasks;
//using System.Collections.Generic;
//using Google.GenAI;
//using Google.GenAI.Types;

//namespace FinCure.Services
//{
//    public class GeminiService
//    {
//        private readonly HttpClient _httpClient;  //Insted of manually sening request to gemini , it takes care of it by using HttpClient
//        private readonly string _apiKey; // gemini needs to know who is using so authentication need for that we need to provide api key

//        public GeminiService(    // Dependencies are injected through constructor
//            HttpClient httpClient,
//            IOptions<GeminiSettings> options)
//        {
//            _httpClient = httpClient;
//            _apiKey = options.Value.ApiKey;
//        }

//        public async Task<string> GenerateRecommendationAsync(
//            string prompt)  // this method will take user input a promt and return a string which is the recommendation generated by gemini
//        {
//            var url =
//                $"https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent?key={_apiKey}";
//            //address for the gemini api endpoint and we need to pass the api key as query parameter for authentication

//            var requestBody = new // gemini api expects the request body to be in a specific format so we need to create an anonymous type that matches that format
//            {
//                contents = new[]
//                {
//                    new
//                    {
//                        parts = new[]
//                        {
//                            new
//                            {
//                                text = prompt
//                            }
//                        }
//                    }
//                }
//            };

//            var content =
//                new StringContent(
//                    JsonSerializer.Serialize(requestBody),  // converts the request body object to a json string
//                    Encoding.UTF8,
//                    "application/json");

//            var response =
//                await _httpClient.PostAsync(url, content);

//            var responseContent =
//    await response.Content.ReadAsStringAsync();

//            Console.WriteLine(responseContent);

//            if (!response.IsSuccessStatusCode)
//            {
//                throw new Exception(
//                    $"Status: {response.StatusCode}\n{responseContent}");
//            }
//            using JsonDocument doc =
//                JsonDocument.Parse(responseContent);

//            return doc
//                .RootElement
//                .GetProperty("candidates")[0]
//                .GetProperty("content")
//                .GetProperty("parts")[0]
//                .GetProperty("text")
//                .GetString()!;
//        }
//    }
//}


using Google.GenAI;
using Google.GenAI.Types;
using FinCure.Configurations;
using Microsoft.Extensions.Options;

namespace FinCure.Services
{
    public class GeminiService
    {
        private readonly string _apiKey;

        public GeminiService(IOptions<GeminiSettings> options)
        {
            _apiKey = options.Value.ApiKey;
        }
        

        public async Task<string> GenerateRecommendationAsync(
            string prompt, object config)
        {
            try
            {
                var client = new Client(
                    apiKey: _apiKey);

                var contents = new List<Content>
                {
                    new Content
                    {
                        Role = "user",
                        Parts = new List<Part>
                        {
                            new Part
                            {
                                Text = prompt
                            }
                        }
                    }
                };

                string result = "";

                await foreach (var chunk in
                    client.Models.GenerateContentStreamAsync(
                        model: "gemini-3.5-flash",
                        contents: contents))
                {
                    result += chunk.Text;
                }

                return result;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);

                return "AI recommendation service is currently unavailable.";
            }
        }
    }
}